# src/obstacle_challenge/config.py
# Configuration for the 4-step absolute heading maneuver.

import numpy as np

# --- Safety Configuration ---
TILT_THRESHOLD_DEGREES = 15.0

# --- Driving & Steering Configuration ---
DRIVE_SPEED = 100.0

# --- Vision & FOV Configuration ---
FRAME_WIDTH = 640; FRAME_HEIGHT = 480; MAX_FPS = 30
CROP_TOP_FRAC = 5/12; CROP_BOTTOM_FRAC = 0
MIN_CONTOUR_AREA = 2500
MAX_BLOCK_AREA_FRACTION = 0.25
MIN_BLOCK_ROI_OVERLAP = 0.50

# --- Behavior Constants ---
MIN_BLOCK_AREA_FOR_ACTION = 7500
MANEUVER_ANGLE_DEG = 45.0
MIN_FRAMES_IN_TURN = 20
TOTAL_TURNS = 12
MANEUVER_DRIVE_FRAMES_SIDEWAYS = 30
MANEUVER_DRIVE_FRAMES_STRAIGHT = 20

# --- HSV Color Ranges (Tuned) ---
LOWER_RED_1 = np.array([0, 150, 80]); UPPER_RED_1 = np.array([10, 255, 255])
LOWER_RED_2 = np.array([170, 150, 80]); UPPER_RED_2 = np.array([180, 255, 255])
LOWER_GREEN = np.array([36, 50, 70]); UPPER_GREEN = np.array([89, 255, 255])

# --- Gyroscope Configuration ---
GYRO_ENABLED = True
GYRO_KP = 3.0
HEADING_LOCK_TOLERANCE = 7.0

# --- Time-of-Flight (ToF) Sensor Configuration ---
TOF_ENABLED = True
TOF_CHANNELS_TO_USE = range(0, 3)
TOF_FORWARD_SENSOR_CHANNEL = 1
TOF_CORNERING_THRESHOLD_MM = 100
TOF_OBSTACLE_THRESHOLD_MM = 100

# --- Hardware Pin & PWM Configuration ---
AIN1_PIN = 26; AIN2_PIN = 13; STBY_PIN = 6
MOTOR_PWM_PIN = 19; MOTOR_PWM_FREQ = 10000; MOTOR_PWM_CHIP = 0; MOTOR_PWM_CHANNEL = 3
SERVO_GPIO = 18; SERVO_PWM_FREQ = 50; SERVO_PWM_CHIP = 0; SERVO_PWM_CHANNEL = 2
CALIBRATED_MIN_PW_S = 0.001; CALIBRATED_MAX_PW_S = 0.002
CALIBRATED_ANGLE_MIN = 45.0; CALIBRATED_ANGLE_MAX = 135.0
INPUT_ANGLE_MIN_SERVO = -45.0; INPUT_ANGLE_MAX_SERVO = 45.0
SAFETY_MIN_PW_S = 0.0005; SAFETY_MAX_PW_S = 0.0025
SERVO_PWM_PERIOD_S = 1.0 / SERVO_PWM_FREQ

# --- Internal Constants ---
BOX_COLOR_RED = (0, 0, 255); BOX_COLOR_GREEN = (0, 255, 0); BOX_COLOR_ROI = (255, 0, 255)
