TILT_THRESHOLD_DEGREES = 15.0


DRIVE_SPEED = 100
TARGET_DISTANCE = 200
KP = 0.25
TOTAL_TURNS = 12
FINAL_FOLLOW_DURATION_S = 1.5

START_CLOSE_WALL_THRESHOLD = 70


LEFT_SENSOR_CHANNEL = 0
RIGHT_SENSOR_CHANNEL = 2


GYRO_ENABLED = True
GYRO_KP = 2.5
HEADING_LOCK_TOLERANCE = 5.0
GYRO_MAX_STEER_LEFT = 20.0
GYRO_MAX_STEER_RIGHT = 36.0
